package com.vibegraph.graph.service;

import java.nio.file.Path;
import java.util.List;

import com.vibegraph.graph.dto.request.CreateProjectRequest;
import com.vibegraph.graph.dto.response.ProjectResponse;

/**
 * Project management service - register, list, get, delete, and analysis status transitions.
 */
public interface ProjectService {

    ProjectResponse createProject(CreateProjectRequest request);

    /**
     * Register a project from a server-owned archive workspace (archive-upload flow).
     *
     * <p>Unlike {@link #createProject(CreateProjectRequest)}, the path is generated by the
     * server (not user-supplied) and is validated to live under the configured archive
     * workspace root rather than the user-input {@code allowed-root}.
     *
     * @param name            display name (blank -> a generated id is used)
     * @param workspaceSource server-owned source directory under the archive workspace root
     */
    ProjectResponse createProjectFromWorkspace(String name, Path workspaceSource);

    /**
     * Register an empty, server-owned workspace for CLI push. Unlike archive/GitHub import,
     * this persists the Project metadata immediately so MCP/source tools can recover the
     * workspace after a backend restart before the first analysis has run.
     *
     * @param name            display name (blank -> a generated id is used)
     * @param workspaceSource empty source directory under the archive workspace root
     */
    ProjectResponse createEmptyWorkspaceProject(String name, Path workspaceSource);

    List<ProjectResponse> listProjects();

    ProjectResponse getProject(String id);

    void deleteProject(String id);

    /**
     * Backward-compatible alias that delegates to {@link #markAnalyzed(String, int, int, int)}.
     */
    void updateProjectStats(String id, int totalFiles, int totalNodes, int totalEdges);

    /** Transition a project to ANALYZING (analysis started). No-op if the project is unknown. */
    void markAnalyzing(String id);

    /**
     * Update only the in-flight analysis progress (0..100) of an ANALYZING project,
     * without changing its status or stats. No-op if the project is unknown. Lets the
     * polling fallback observe intermediate progress, not just 0 -> 100.
     */
    void updateProgress(String id, int progress);

    /** Transition a project to ANALYZED with final stats + lastAnalyzedAt. No-op if unknown. */
    void markAnalyzed(String id, int totalFiles, int totalNodes, int totalEdges);

    /** Transition a project to FAILED, preserving existing metadata. No-op if unknown. */
    void markFailed(String id, String reason);
}
