export const publicSiteCopy = {
  'en-US': {
    nav: { workflow: 'Workflow', proof: 'What is verified', docs: 'Docs' },
    actions: { login: 'Log in', dashboard: 'Open dashboard', readDocs: 'Read the production setup' },
    landing: {
      skip: 'Skip to content',
      heroEyebrow: 'SOURCE-CODE INTELLIGENCE / VIBEGRAPH.TECH',
      heroTitle: 'See your code as a graph.',
      heroBody: 'VibeGraph maps Java projects into searchable classes, methods, and relationships, then exposes impact and context through the dashboard and MCP.',
      heroNote: 'Project API keys stay scoped to one project. The CLI proxy keeps the raw key out of generated IDE JSON.',
      graphTitle: 'Interactive architecture graph',
      graphSubtitle: 'Select a node to inspect its connected surface.',
      graphSelected: 'Selected symbol',
      graphHint: 'Click a node · press Enter to focus',
      verifiedWorkflow: 'Documented VibeGraph workflow',
      verifiedLabel: 'documented workflow',
      loginSuccess: 'Authenticated in browser',
      selectedKey: 'Selected: <owned project key>',
      proxySuccess: 'MCP proxy written without raw key',
      consoleFooter: 'CLI → project key → MCP proxy → analyzed project',
      workflowEyebrow: 'THE WORKFLOW',
      workflowTitle: 'From a repository to a dependable context surface.',
      workflowBody: 'Each step maps to a real product surface already present in the repository and documented CLI.',
      flows: [
        ['01', 'Import a Java project', 'Use the web app, CLI Push, an archive, or a public GitHub URL to create the project graph.'],
        ['02', 'Read the graph', 'Explore classes, methods, relationships, source snippets, and execution-flow context in the dashboard.'],
        ['03', 'Connect an agent', 'Authenticate with a project-bound key, then let an MCP client query the same analyzed project.'],
      ],
      proofEyebrow: 'NO MARKETING NUMBERS',
      proofTitle: 'What this page can prove today.',
      proofBody: 'We removed simulated counters and demo output from the public promise. These are the implementation facts we can point to.',
      proofPoints: [
        'Spring Boot backend with a Neo4j graph store',
        'Vue 3 dashboard with Sigma.js graph rendering',
        'MCP server at /mcp with project ownership checks',
        'CLI commands for login, key selection, push, watch, and MCP install',
      ],
      ctaEyebrow: 'NEXT STEP',
      ctaTitle: 'Ready to work from the same graph?',
      ctaBody: 'Open the dashboard if you already have an account, or start with the documented browser login and project-key flow.',
      footer: 'Source-code intelligence for the vibe-coding era.',
      documentation: 'Documentation',
    },
    docs: {
      navLabel: 'Documentation navigation', back: 'Back to VibeGraph', onPage: 'On this page', titleLabel: 'Production docs', importNav: 'Import',
      sideLinks: ['Release status', 'Install and login', 'Download for AI', 'CLI Push / Watch', 'CLI commands', 'MCP setup', '18 MCP tools', 'Key changes and errors', 'Troubleshooting', 'Video plan'],
      eyebrow: 'VIBEGRAPH.TECH / DOCUMENTATION', title: 'Install the CLI. Point your IDE at the right project.',
      intro: 'This guide only documents flows present in the VibeGraph CLI, backend tests, or repository docs. It does not promise a feature that has not been verified.',
      releaseTitle: 'Release status checked locally',
      releaseBody: 'The npm registry currently serves vibegraph-cli@0.1.7 as latest. Install it globally with npm install -g vibegraph-cli, then run vibegraph login to choose a project key in the browser. This version includes the MCP handshake probe, tool-list check, request timeout, stale-config repair, fuzzy command suggestions, project graph counts, clear asynchronous analysis feedback, reliable hidden password prompts, and automatic update notifications.',
      installTitle: 'Install and login', installLead: 'Production browser login proves the signed-in user owns the project key before the CLI stores it.',
      installBody: 'vibegraph login opens the browser authorization flow. After sign-in, choose an active project key owned by your account. Raw-key shortcuts are rejected because a key alone cannot prove account ownership.',
      downloadsTitle: 'Download a guide for your AI assistant', downloadsLead: 'Download the same verified setup instructions as Markdown or standalone HTML, then attach the file to ChatGPT, Claude, Cursor, Kiro, or your team workspace.', downloadsMd: 'Download', downloadsHtml: 'Download', downloadsNote: 'The guide tells an AI not to request secrets, invent project data, or assume a command succeeded. It is a static handoff document and does not execute commands.',
      importTitle: 'Choose an import path', importLead: 'Pick the path that matches where your source code lives. The result is the same: VibeGraph registers a project, analyzes Java source, and makes the graph available to the dashboard and MCP.',
      importCards: [
        ['CLI Push', 'Your source is on this computer and you want future updates.', 'cd <LOCAL_PROJECT_FOLDER>\nvibegraph login\nvibegraph push --dry-run\nvibegraph push', 'Best for: active development. Run push again after edits or use watch.'],
        ['Archive upload', 'You have a ZIP/TAR/TAR.GZ/TGZ file and do not need a live local link.', 'Open Dashboard → Projects → Import archive\nChoose the file\nStart analysis', 'Best for: sharing a snapshot or importing from another machine.'],
        ['Public GitHub', 'The repository is public and available at a GitHub HTTPS URL.', 'Open Dashboard → Projects → Import GitHub\nhttps://github.com/<owner>/<repo>\nChoose a branch (optional)', 'Best for: importing a public repository without downloading it first.'],
      ],
      importNote: 'Import billing and limits are enforced by the backend. The docs intentionally do not invent credit amounts or analysis times.',
      importDemoTitle: 'See the import hand-off', importDemoLead: 'This visual walkthrough shows what the user does and what the product hands to the backend. It is a documentation simulation: no file is uploaded and no project is created.', importDemoDisclaimer: 'Illustrative import flow — no upload or analysis started', importDemoIdle: 'The walkthrough starts automatically when it enters the viewport.', importDemoSteps: ['Choose a source', 'Validate and submit', 'Backend registers and analyzes', 'Graph becomes available to dashboard/MCP'],
      updateTitle: 'Update an existing CLI', updateBody: 'For a clean update, remove the old global package before installing the latest published version. This avoids stale Windows command shims. Never paste a project API key into npm.',
      pushTitle: 'CLI Push and Watch', pushLead: 'Run push or watch inside the project folder. The selected project key decides which VibeGraph project receives the changes.',
      firstPushTitle: 'First push', firstPushBody: 'Before the first push, create the destination project and an active project API key in the web dashboard. Browser login selects that owned key. Dry-run scans the folder without sending a patch; push sends the changed files to the key-bound project.',
      updatePushTitle: 'Update the analyzed project', updatePushBody: 'After editing source files, run push again from the same folder. The CLI compares its local snapshot and sends only changed/deleted files. Use watch when you want continuous updates.',
      pushMcpTitle: 'How Push and MCP work together', pushMcpBody: 'Push updates the project graph. MCP reads that same analyzed project through the selected key. Push is not an MCP install step: configure MCP once, then push whenever the code changes.',
      pushBody: 'The CLI safety rules skip secrets, archives, binary files, symlinks, build folders, and files over the configured limit. Press Ctrl+C to stop watch mode.',
      commandsTitle: 'VibeGraph CLI command reference', commandsBody: 'Run these commands in a normal terminal. The CLI uses the current folder by default, so the common workflow stays short. Inside the interactive vibegraph> shell, omit the executable prefix and enter only the command text.',
      commands: [
        ['vibegraph update', 'Install the latest CLI version; Enter accepts the update prompt.'],
        ['vibegraph --version', 'Show the installed CLI version.'], ['vibegraph help', 'Show the complete command reference.'], ['vibegraph config show', 'Show the API URL, config path, account state, and masked key state.'], ['vibegraph config set-url <url>', 'Set the backend URL; production uses https://api.vibegraph.tech.'], ['vibegraph config reset', 'Remove the local CLI config file.'], ['vibegraph register --email <email> --password <password> --name <name>', 'Create an account and save its account session.'], ['vibegraph login', 'Open browser login and select an owned project API key.'], ['vibegraph login --email <email> --password <password>', 'Sign in directly with account credentials for account-level project management.'], ['vibegraph logout', 'Clear the saved account session, project key, project selection, and cached key metadata.'], ['vibegraph me', 'Show the account attached to a valid JWT session.'], ['vibegraph doctor', 'Check backend health, JWT session validity, and selected API key status.'], ['vibegraph key list', 'Show cached masked key/project metadata.'], ['vibegraph key change', 'Refresh owned keys and select another project key.'], ['vibegraph key status', 'Show masked selected-key state.'], ['vibegraph key clear', 'Clear the selected project key; this is the same operation as auth clear.'], ['vibegraph auth status', 'Show selected API key status and whether a legacy account token is stored.'], ['vibegraph auth clear', 'Clear the selected project key without deleting the account.'], ['vibegraph push', 'Scan the current folder and send a patch to the selected project key.'], ['vibegraph push --dry-run', 'Preview changed, deleted, and skipped files without sending a patch.'], ['vibegraph watch', 'Watch the current folder and push changes continuously.'], ['vibegraph ignore init', 'Create a .vibegraphignore file for project-specific scan exclusions.'], ['vibegraph projects list', 'List projects through the account session, not the project API key.'], ['vibegraph projects create --path <backendPath>', 'Register a path visible to the backend host; this is not a local-folder upload.'], ['vibegraph projects import-local --path <backendPath>', 'Import a backend/container-visible path.'], ['vibegraph projects analyze', 'Analyze the project selected by the active project key; projectId remains a legacy compatibility form.'], ['vibegraph projects status', 'Show status for the project selected by the active project key; projectId remains a legacy compatibility form.'], ['vibegraph projects push [--root <localPath>] [--dry-run]', 'Push the current or chosen local folder to the selected project.'], ['vibegraph projects delete', 'List account projects, choose by number, and confirm before deletion.'], ['vibegraph mcp install <cursor|vscode|generic>', 'Write/update an IDE MCP config and verify the handshake.'], ['vibegraph mcp config <cursor|vscode|generic>', 'Print JSON for manual copy/paste; it does not edit IDE files.'], ['vibegraph mcp doctor', 'Verify MCP initialize/tools/list and report the available tool count.'], ['vibegraph mcp-proxy --stdio', 'Internal stdio bridge used by IDE MCP clients; do not type it inside the interactive shell.'],
      ],
      mcpTitle: 'MCP setup', mcpLead: 'There are two ways to add VibeGraph MCP. Automatic install edits the IDE config for you. Manual setup means either generating stdio JSON or pasting the remote HTTP JSON. Choose one method per VibeGraph server entry, then restart or reload the IDE MCP connection.',
      autoMcpTitle: '1. Automatic install', autoMcpBody: 'After vibegraph login, the CLI writes or updates the correct config file and runs an initialize/tools-list check. Cursor uses mcpServers in ~/.cursor/mcp.json; VS Code uses servers in .vscode/mcp.json; generic writes mcp.json unless --path is supplied.',
      generatedMcpTitle: '2A. Manual stdio config — generate JSON', generatedMcpBody: 'mcp config only prints configuration; it does not edit any IDE file. generic and cursor output the standard mcpServers shape. vscode outputs VS Code\'s servers shape. Paste the complete object into the IDE MCP settings. This is the manual version of the same local CLI proxy used by automatic install.',
      localStdioTitle: '2B. Manual stdio config — installed CLI path', localStdioBody: 'This JSON runs the globally installed CLI on the local machine. Replace both Windows paths: the Node executable and the user-specific vibegraph-cli installation. Never copy another user\'s C:\\Users\\... path unchanged. Prefer vibegraph mcp config cursor, which generates the correct paths automatically.',
      mcpBody: 'If tools do not appear after installation, run vibegraph mcp doctor, then restart or reload the IDE MCP server. Doctor verifies initialize and tools/list; after that, call list_projects once from the IDE to verify a real tool response. Do not paste the vibegraph> prompt and do not nest a second mcpServers object.',
      mcpToolsTitle: '18 MCP tools: what each one is for', mcpToolsLead: 'The list below is taken from the tool registry in the backend MCP module. Project-scoped tools use the project bound to the API key automatically; you do not need to type projectId in normal use.',
      mcpTools: [
        ['get_project_architecture', 'Architecture overview: layers, counts, conventions, detected patterns, and warnings.', 'Ask for a quick map before touching an unfamiliar Java service.'],
        ['get_class_context', 'Inspect a class: methods, fields, incoming relations, outgoing relations, and warnings.', 'Use it when you need to understand one controller or service in context.'],
        ['get_impact_analysis', 'Calculate blast radius and risk for a graph node with dependency, structural, or type-data-flow profiles.', 'Run before changing a public method to see likely callers and affected paths.'],
        ['get_layer_pattern', 'Show examples and dependency conventions for a layer such as CONTROLLER, SERVICE, or REPOSITORY.', 'Use it to match the project style when adding a new class.'],
        ['trace_endpoint', 'Trace an HTTP method and route from endpoint mapping to handler and downstream flow.', 'Use it to follow `POST /api/orders` before changing request behavior.'],
        ['find_references', 'Find incoming, outgoing, or both graph references to a class, method, interface, or field.', 'Use it to locate every caller of a renamed method.'],
        ['get_source_file', 'Read a bounded, redacted slice of a project source file.', 'Use it when the graph points to a file and you need the exact nearby code.'],
        ['search_source', 'Perform literal source search and map matching files to graph symbols when possible.', 'Use it to find a feature flag, annotation, or error message.'],
        ['get_method_source', 'Read the exact source body of one method or constructor by ID, signature, or unambiguous name.', 'Use it after impact analysis to inspect the implementation you will edit.'],
        ['get_method_cpg_context', 'Return grouped code-property-graph context: calls, flow groups, and bounded method detail.', 'Use it for data-flow or control-flow questions inside a method.'],
        ['find_related_tests', 'Find tests related to a symbol, method, class, or file using graph links and bounded heuristics.', 'Use it to identify regression tests before creating a patch.'],
        ['suggest_test_plan', 'Suggest a layered test plan for a described change, with risk and target context.', 'Use it at the start of a feature to plan unit, integration, and security checks.'],
        ['plan_code_change', 'Create a conservative senior-style change plan with candidate files, risks, and tests.', 'Use it when the request is broad and you want an evidence-backed plan first.'],
        ['explain_failure_path', 'Map a Java stack trace, failing test, or error message back to project code.', 'Use it after CI reports a failure and you need likely source locations.'],
        ['get_project_conventions', 'Return durable repository conventions and known facts from the project memory file.', 'Use it before editing so generated code follows local rules.'],
        ['list_projects', 'List analyzed projects owned by the authenticated caller with status and graph statistics.', 'Use it to verify the account can see projects; project keys remain project-bound.'],
        ['verify_change', 'Review changed files, reachable API routes, related tests, and suggested verification commands.', 'Use it as a pre-completion safety check before saying a change is done.'],
        ['explain_compile_error', 'Map javac or Maven compiler output to enclosing symbols, callers, and fix hints.', 'Use it when a build log is noisy and you need an actionable explanation.'],
      ],
      mcpExamplesTitle: 'Prompt → tool call → answer (illustrative)', mcpExamplesLead: 'Choose a scenario, then run the small simulation to see the order an agent conversation normally follows. No production MCP request is sent and no telemetry is invented.',
      simulationDisclaimer: 'Illustrative simulation — no live MCP call', simulationToolStatus: 'Tool call completed with the selected project context (example response).', simulationIdle: 'The conversation starts automatically when it enters the viewport.', simulationTyping: 'Agent is composing the MCP request…',
      mcpExamples: [
        ['Find change risk', 'I want to rename OrderService.createOrder. What could break?', 'get_impact_analysis', 'The agent would inspect the selected project, report direct and transitive callers, highlight route/test impact, and recommend verification before editing.'],
        ['Trace an API route', 'How does POST /api/orders reach the database?', 'trace_endpoint', 'The agent would return the mapped controller, service calls, repository boundary, and any missing or ambiguous route links.'],
        ['Turn a build log into fixes', 'Explain this Maven error and point me to the affected code.', 'explain_compile_error', 'The agent would map compiler lines to enclosing symbols, show caller counts, and suggest the smallest verification commands.'],
      ],
      manualTitle: '2C. Manual Streamable HTTP', manualBody: 'PROJECT_API_KEY must be an active key created for the exact project. Store it in the IDE secret/environment store, not in a committed workspace file.',
      keysTitle: 'Change keys and recover from errors',
      keysBody: "After key change, restart or reload the IDE MCP connection. Deleted, rotated, disabled, or expired keys are rejected. The browser selector only returns keys owned by the signed-in account, and MCP rejects a tool request that targets a project different from the key's bound project.",
      keyMeaning: 'In manual HTTP mode, replace the X-API-Key value and reload MCP. The key identifies the project; it is not an OAuth secret, JWT secret, or account-wide credential.',
      creditTitle: 'Credit metering', creditBody: 'Metered MCP calls calculate the MCP_TOOL_CALL price and reserve the credit debit before running the delegated tool. The ledger records the MCP channel and bound project. If the debit fails, the tool does not run; a tool failure after the reserved debit remains charged.',
      troubleshootingTitle: 'Common fixes', troubleshootingBody: 'Use the smallest diagnostic command first. These commands and messages match the current CLI behavior.',
      troubleshooting: [
        ['npm says EEXIST: file already exists', 'A stale global command shim is blocking the update. Uninstall the package, remove only the VibeGraph shims if they remain, then install again.', 'npm uninstall -g vibegraph-cli\nRemove-Item "$env:APPDATA\\npm\\vibegraph.cmd","$env:APPDATA\\npm\\vibegraph.ps1","$env:APPDATA\\npm\\vibegraph-cli.cmd","$env:APPDATA\\npm\\vibegraph-cli.ps1" -Force -ErrorAction SilentlyContinue\nnpm install -g vibegraph-cli@latest'],
        ['The terminal says Unknown command: vibegraph', 'Inside the interactive prompt, type the command without the executable prefix. The prefix is only for a normal terminal command.', 'vibegraph> push\nvibegraph> key status\nvibegraph> doctor'],
        ['MCP was added but no tools appear', 'Run the CLI probe, then reload the IDE MCP server. If the probe is ready but the IDE is empty, the IDE is reading another config file or has not restarted. Once tools appear, call list_projects once from the IDE.', 'vibegraph mcp doctor\nvibegraph mcp install cursor\n# Restart or reload the IDE MCP server\n# Then call list_projects'],
        ['MCP doctor says the key is invalid', 'The selected project key was deleted, rotated, disabled, expired, or is not owned by the signed-in account. Select a fresh owned key.', 'vibegraph key change\nvibegraph mcp doctor'],
        ['projects list returns HTTP 401', 'Project management uses an account JWT; a project API key is intentionally project-bound and is not an account-wide session.', 'vibegraph login --email <email> --password <password>\nvibegraph projects list'],
      ],
      videosTitle: 'Tutorial videos — will be recorded later', videosBody: 'Each card is a separate recording session. I will only operate Chrome after you send its number, then stop where you can save the video.',
      videoFooter: 'Prerequisites, expected result, and the OBS stop point will be prepared before recording.',
      videos: [
        ['1', 'Install the CLI and complete browser login', 'npm install -g vibegraph-cli → vibegraph login'],
        ['2', 'Select or change the project key', 'vibegraph key list → vibegraph key change'],
        ['3', 'Push a real project', 'vibegraph push'],
        ['4', 'Install MCP for Cursor', 'vibegraph mcp install cursor'],
        ['5', 'Install MCP for VS Code or a generic IDE', 'vibegraph mcp install vscode|generic'],
        ['6', 'Configure MCP HTTP manually', 'Paste JSON and replace <PROJECT_API_KEY>'],
        ['7', 'Call a tool and inspect credits', 'Only with a safe test account/project'],
      ],
    },
  },
  'vi-VN': {
    nav: { workflow: 'Quy trình', proof: 'Bằng chứng', docs: 'Tài liệu' },
    actions: { login: 'Đăng nhập', dashboard: 'Mở dashboard', readDocs: 'Xem hướng dẫn production' },
    landing: {
      skip: 'Bỏ qua điều hướng', heroEyebrow: 'TRÍ TUỆ MÃ NGUỒN / VIBEGRAPH.TECH',
      heroTitle: 'Hiểu code qua graph.',
      heroBody: 'VibeGraph ánh xạ project Java thành class, method và relationship có thể tìm kiếm, sau đó cung cấp impact và context qua dashboard và MCP.',
      heroNote: 'API key được giới hạn theo từng project. CLI proxy không ghi raw key vào JSON IDE được tạo.',
      graphTitle: 'Graph kiến trúc tương tác',
      graphSubtitle: 'Chọn một node để xem vùng liên kết của nó.',
      graphSelected: 'Symbol đang chọn',
      graphHint: 'Bấm node · nhấn Enter để focus',
      verifiedWorkflow: 'Quy trình CLI/MCP được tài liệu hóa', verifiedLabel: 'quy trình được tài liệu hóa',
      loginSuccess: 'Xác thực thành công trên trình duyệt', selectedKey: 'Đã chọn: <project key thuộc tài khoản>',
      proxySuccess: 'Đã ghi MCP proxy, không chứa raw key', consoleFooter: 'CLI → project key → MCP proxy → project đã phân tích',
      workflowEyebrow: 'QUY TRÌNH', workflowTitle: 'Từ repository đến một nguồn context đáng tin cậy.',
      workflowBody: 'Mỗi bước đều tương ứng với một bề mặt sản phẩm có thật trong repository và CLI hiện tại.',
      flows: [
        ['01', 'Import project Java', 'Dùng web app, CLI Push, archive hoặc URL GitHub public để tạo project graph.'],
        ['02', 'Đọc graph', 'Khám phá class, method, relationship, source snippet và execution-flow context trên dashboard.'],
        ['03', 'Kết nối agent', 'Xác thực bằng project key, sau đó cho MCP client truy vấn đúng project đã phân tích.'],
      ],
      proofEyebrow: 'KHÔNG DÙNG SỐ LIỆU MARKETING', proofTitle: 'Những gì trang này chứng minh được hôm nay.',
      proofBody: 'Các counter và output demo mô phỏng đã bị loại khỏi lời hứa công khai. Đây là các dữ kiện có thể đối chiếu trong implementation.',
      proofPoints: ['Backend Spring Boot với graph store Neo4j', 'Dashboard Vue 3 render graph bằng Sigma.js', 'MCP server tại /mcp có kiểm tra quyền sở hữu project', 'CLI có lệnh login, chọn key, push, watch và cài MCP'],
      ctaEyebrow: 'BƯỚC TIẾP THEO', ctaTitle: 'Sẵn sàng làm việc trên cùng một graph?',
      ctaBody: 'Mở dashboard nếu bạn đã có tài khoản, hoặc bắt đầu bằng quy trình browser login và project key trong tài liệu.',
      footer: 'Trí tuệ mã nguồn cho thời đại vibe coding.', documentation: 'Tài liệu',
    },
    docs: {
      navLabel: 'Điều hướng tài liệu', back: 'Về trang chủ', onPage: 'Trong trang này', titleLabel: 'Tài liệu production', importNav: 'Import',
      sideLinks: ['Trạng thái phát hành', 'Cài đặt và đăng nhập', 'Tải tài liệu cho AI', 'CLI Push / Watch', 'Danh sách lệnh CLI', 'Cài MCP', '18 tool MCP', 'Đổi key và xử lý lỗi', 'Xử lý lỗi thường gặp', 'Kế hoạch video'],
      eyebrow: 'VIBEGRAPH.TECH / TÀI LIỆU', title: 'Cài CLI. Trỏ IDE vào đúng project.',
      intro: 'Hướng dẫn này chỉ ghi các flow có trong VibeGraph CLI, backend test hoặc tài liệu repository. Không hứa một chức năng chưa được kiểm chứng.',
      releaseTitle: 'Trạng thái phát hành đã kiểm tra', releaseBody: 'npm registry hiện đang phục vụ vibegraph-cli@0.1.7 ở tag latest. Cài global bằng npm install -g vibegraph-cli, sau đó chạy vibegraph login để chọn project key trên trình duyệt. Bản này đã có probe MCP, kiểm tra tools, timeout cho request, gợi ý lệnh linh hoạt, số node/edge của graph, thông báo rõ khi analyze chạy nền, nhập password ẩn ổn định, tự sửa config cũ và thông báo cập nhật tự động.',
      installTitle: 'Cài đặt và đăng nhập', installLead: 'Browser login production chứng minh người đang đăng nhập sở hữu project key trước khi CLI lưu key.',
      installBody: 'vibegraph login mở luồng xác nhận trên trình duyệt. Sau khi đăng nhập, chọn một project key active thuộc tài khoản của bạn. Các cách nhập raw key bị từ chối vì bản thân key không chứng minh được quyền sở hữu tài khoản.',
      downloadsTitle: 'Tải tài liệu cho AI assistant', downloadsLead: 'Tải cùng một bộ hướng dẫn đã kiểm chứng ở dạng Markdown hoặc HTML độc lập, rồi đính kèm cho ChatGPT, Claude, Cursor, Kiro hoặc workspace của team.', downloadsMd: 'Tải xuống', downloadsHtml: 'Tải xuống', downloadsNote: 'Tài liệu nhắc AI không yêu cầu secret, không bịa dữ liệu project và không giả định lệnh đã thành công. Đây là file bàn giao tĩnh, không tự chạy lệnh.',
      importTitle: 'Chọn cách import', importLead: 'Chọn cách phù hợp với nơi source đang nằm. Kết quả giống nhau: VibeGraph đăng ký project, phân tích source Java và cung cấp graph cho dashboard/MCP.',
      importCards: [
        ['CLI Push', 'Source nằm trên máy bạn và bạn muốn cập nhật liên tục.', 'cd <LOCAL_PROJECT_FOLDER>\nvibegraph login\nvibegraph push --dry-run\nvibegraph push', 'Phù hợp: phát triển hằng ngày. Sửa code rồi push lại hoặc dùng watch.'],
        ['Upload archive', 'Bạn có file ZIP/TAR/TAR.GZ/TGZ và không cần liên kết thư mục local.', 'Mở Dashboard → Projects → Import archive\nChọn file\nBắt đầu phân tích', 'Phù hợp: chia sẻ snapshot hoặc import từ máy khác.'],
        ['GitHub public', 'Repository public và có URL HTTPS GitHub.', 'Mở Dashboard → Projects → Import GitHub\nhttps://github.com/<owner>/<repo>\nChọn branch nếu cần', 'Phù hợp: import repo public mà không cần tải về trước.'],
      ],
      importNote: 'Billing và giới hạn import do backend áp dụng. Docs không tự bịa số credit hoặc thời gian phân tích.',
      importDemoTitle: 'Xem luồng bàn giao import', importDemoLead: 'Mô phỏng trực quan này cho thấy người dùng làm gì và sản phẩm bàn giao gì cho backend. Đây chỉ là mô phỏng tài liệu: không upload file và không tạo project thật.', importDemoDisclaimer: 'Luồng import minh họa — chưa upload hay phân tích thật', importDemoIdle: 'Walkthrough sẽ tự chạy khi đi vào vùng nhìn thấy.', importDemoSteps: ['Chọn source', 'Kiểm tra và gửi', 'Backend đăng ký và phân tích', 'Graph có trên dashboard/MCP'],
      updateTitle: 'Cập nhật CLI đã cài', updateBody: 'Để cập nhật sạch, gỡ package global cũ trước khi cài bản published mới. Cách này tránh command shim Windows cũ. Không dán project API key vào npm.',
      pushTitle: 'CLI Push và Watch', pushLead: 'Chạy push hoặc watch ngay trong thư mục dự án. Project key đã chọn quyết định project VibeGraph nhận thay đổi.',
      firstPushTitle: 'Push lần đầu', firstPushBody: 'Trước lần push đầu, tạo project đích và một project API key active trên web dashboard. Browser login dùng để chọn key thuộc tài khoản đó. Dry-run quét thư mục nhưng không gửi patch; push gửi file thay đổi tới project được bind với key.',
      updatePushTitle: 'Cập nhật project đã phân tích', updatePushBody: 'Sau khi sửa source, chạy lại push trong cùng thư mục. CLI đối chiếu snapshot local và chỉ gửi file changed/deleted. Dùng watch nếu muốn cập nhật liên tục.',
      pushMcpTitle: 'Push kết hợp với MCP như thế nào', pushMcpBody: 'Push cập nhật graph của project. MCP đọc chính project đã phân tích đó bằng key đang chọn. Push không thay cho bước cài MCP: cài MCP một lần, sau đó push mỗi khi code thay đổi.',
      pushBody: 'CLI tự bỏ qua secret, archive, binary, symlink, thư mục build và file vượt giới hạn cấu hình. Nhấn Ctrl+C để dừng watch mode.',
      commandsTitle: 'Danh sách lệnh VibeGraph CLI', commandsBody: 'Chạy các lệnh này trong terminal bình thường. CLI tự dùng thư mục hiện tại nên workflow phổ biến không cần tham số đường dẫn. Trong interactive shell vibegraph>, bỏ phần tên executable và chỉ nhập nội dung lệnh.',
      commands: [
        ['vibegraph update', 'Cài bản CLI mới nhất; Enter để chấp nhận lời nhắc cập nhật.'],
        ['vibegraph --version', 'Xem version CLI đang cài.'], ['vibegraph help', 'Xem toàn bộ danh sách lệnh.'], ['vibegraph config show', 'Xem API URL, config path, trạng thái account và key dạng masked.'], ['vibegraph config set-url <url>', 'Đặt URL backend; production dùng https://api.vibegraph.tech.'], ['vibegraph config reset', 'Xóa file config CLI trên máy.'], ['vibegraph register --email <email> --password <password> --name <name>', 'Tạo tài khoản và lưu account session.'], ['vibegraph login', 'Mở browser login và chọn project API key thuộc tài khoản.'], ['vibegraph login --email <email> --password <password>', 'Đăng nhập trực tiếp để dùng các lệnh quản lý project cấp tài khoản.'], ['vibegraph logout', 'Xóa account session, project key, project đang chọn và metadata key cache.'], ['vibegraph me', 'Xem tài khoản của JWT session còn hiệu lực.'], ['vibegraph doctor', 'Kiểm tra health backend, JWT session và trạng thái key đang chọn.'], ['vibegraph key list', 'Xem metadata key/project dạng masked đã cache.'], ['vibegraph key change', 'Refresh danh sách key thuộc tài khoản và chọn project khác.'], ['vibegraph key status', 'Xem trạng thái key đang chọn dạng masked.'], ['vibegraph key clear', 'Xóa project key đang chọn; cùng chức năng với auth clear.'], ['vibegraph auth status', 'Xem trạng thái project key và việc có lưu legacy account token hay không.'], ['vibegraph auth clear', 'Xóa project key đang chọn trên máy, không xóa tài khoản.'], ['vibegraph push', 'Quét thư mục hiện tại và gửi patch tới project của key đang chọn.'], ['vibegraph push --dry-run', 'Xem trước file changed, deleted và skipped mà không gửi patch.'], ['vibegraph watch', 'Theo dõi thư mục hiện tại và push thay đổi liên tục.'], ['vibegraph ignore init', 'Tạo .vibegraphignore để thêm quy tắc bỏ qua file riêng của project.'], ['vibegraph projects list', 'Liệt kê project bằng account session, không dùng project API key.'], ['vibegraph projects create --path <backendPath>', 'Đăng ký path mà backend host nhìn thấy; không phải upload thư mục local.'], ['vibegraph projects import-local --path <backendPath>', 'Import path mà backend/container nhìn thấy.'], ['vibegraph projects analyze', 'Analyze project đang được chọn bởi project key; projectId vẫn được hỗ trợ cho tương thích legacy.'], ['vibegraph projects status', 'Xem trạng thái project đang được chọn bởi project key; projectId vẫn được hỗ trợ cho tương thích legacy.'], ['vibegraph projects push [--root <localPath>] [--dry-run]', 'Push thư mục hiện tại hoặc thư mục local chỉ định tới project của key đang chọn.'], ['vibegraph projects delete', 'Hiển thị project theo số, chọn project và xác nhận trước khi xóa.'], ['vibegraph mcp install <cursor|vscode|generic>', 'Ghi/cập nhật config MCP IDE và kiểm tra handshake.'], ['vibegraph mcp config <cursor|vscode|generic>', 'In JSON để copy/dán thủ công; không tự sửa file IDE.'], ['vibegraph mcp doctor', 'Kiểm tra MCP initialize/tools/list và báo số lượng tool.'], ['vibegraph mcp-proxy --stdio', 'Cầu nối stdio nội bộ cho IDE MCP; không nhập lệnh này trong interactive shell.'],
      ],
      mcpTitle: 'Cài MCP', mcpLead: 'Có hai cách thêm VibeGraph MCP. Cài tự động sẽ tự sửa file cấu hình IDE. Cài thủ công gồm gen JSON stdio hoặc dán JSON HTTP remote. Chọn một cách cho mỗi entry VibeGraph, sau đó restart hoặc reload kết nối MCP của IDE.',
      autoMcpTitle: '1. Cài tự động', autoMcpBody: 'Sau vibegraph login, CLI tự ghi hoặc cập nhật đúng file cấu hình rồi chạy kiểm tra initialize/tools-list. Cursor dùng mcpServers trong ~/.cursor/mcp.json; VS Code dùng servers trong .vscode/mcp.json; generic ghi mcp.json nếu không truyền --path.',
      generatedMcpTitle: '2A. Cấu hình stdio thủ công — gen JSON', generatedMcpBody: 'mcp config chỉ in cấu hình, không tự sửa file IDE. generic và cursor in dạng chuẩn mcpServers. vscode in dạng servers riêng của VS Code. Dán nguyên object được sinh ra vào MCP settings. Đây là cách thủ công của cùng local CLI proxy mà lệnh tự động sử dụng.',
      localStdioTitle: '2B. Cấu hình stdio thủ công — đường dẫn CLI đã cài', localStdioBody: 'Mẫu JSON này chạy CLI đã cài global trên máy local. Phải sửa cả hai đường dẫn Windows: file Node và thư mục vibegraph-cli theo username/vị trí npm của máy đó. Không copy nguyên đường dẫn C:\\Users\\... của người khác. Nên dùng vibegraph mcp config cursor để CLI tự sinh đúng đường dẫn.',
      mcpBody: 'Nếu cài xong không thấy tool, chạy vibegraph mcp doctor rồi restart hoặc reload MCP server trong IDE. Doctor kiểm tra initialize và tools/list; sau đó gọi list_projects một lần từ IDE để kiểm tra tool call thật có trả kết quả. Không dán prompt vibegraph> và không lồng thêm một tầng mcpServers.',
      mcpToolsTitle: '18 tool MCP: công dụng của từng tool', mcpToolsLead: 'Danh sách này lấy từ registry tool backend. Tool theo project tự dùng project bind với API key; workflow bình thường không cần nhập projectId.',
      mcpTools: [
        ['get_project_architecture', 'Tổng quan layer, số lượng, convention, pattern và cảnh báo.', 'Dùng để hiểu nhanh project Java lạ.'], ['get_class_context', 'Xem class, method, field và các quan hệ.', 'Dùng khi cần hiểu controller hoặc service.'], ['get_impact_analysis', 'Tính blast radius và risk của node.', 'Dùng trước khi sửa method public.'], ['get_layer_pattern', 'Hiển thị pattern và dependency convention của layer.', 'Dùng để viết class mới đúng style.'], ['trace_endpoint', 'Trace route HTTP tới handler và flow phía sau.', 'Dùng để theo dõi một API cụ thể.'], ['find_references', 'Tìm reference incoming, outgoing hoặc cả hai.', 'Dùng để tìm mọi caller.'], ['get_source_file', 'Đọc một vùng source có giới hạn và redacted.', 'Dùng để xem code thật quanh vị trí graph chỉ ra.'], ['search_source', 'Tìm literal trong source và map tới graph symbol.', 'Dùng để tìm flag, annotation hoặc error.'], ['get_method_source', 'Đọc body method/constructor theo ID hoặc signature.', 'Dùng sau impact analysis.'], ['get_method_cpg_context', 'Xem call, flow và nhóm CPG của method.', 'Dùng cho data-flow/control-flow.'], ['find_related_tests', 'Tìm test liên quan tới symbol hoặc file.', 'Dùng trước khi tạo regression test.'], ['suggest_test_plan', 'Đề xuất test plan theo layer và risk.', 'Dùng khi bắt đầu một thay đổi.'], ['plan_code_change', 'Lập change plan với file, risk và test.', 'Dùng cho yêu cầu rộng.'], ['explain_failure_path', 'Map stack trace hoặc test fail về code.', 'Dùng để debug CI.'], ['get_project_conventions', 'Trả convention và facts của repository.', 'Dùng trước khi sửa code.'], ['list_projects', 'Liệt kê project caller được sở hữu và graph stats.', 'Dùng để kiểm tra account/project.'], ['verify_change', 'Kiểm tra file đổi, route, test và lệnh verify.', 'Dùng trước khi kết luận hoàn tất.'], ['explain_compile_error', 'Map lỗi javac/Maven tới symbol và gợi ý sửa.', 'Dùng để biến build log thành hành động.'],
      ],
      mcpExamplesTitle: 'Prompt → tool call → câu trả lời (mô phỏng)', mcpExamplesLead: 'Chọn một tình huống rồi chạy mô phỏng để xem thứ tự một cuộc hội thoại agent thường diễn ra. Không gửi request tới MCP production và không bịa telemetry.',
      simulationDisclaimer: 'Mô phỏng minh họa — không gọi MCP production', simulationToolStatus: 'Tool đã được gọi với project context đã chọn (kết quả ví dụ).', simulationIdle: 'Cuộc hội thoại sẽ tự chạy khi đi vào vùng nhìn thấy.', simulationTyping: 'Agent đang tạo request MCP…',
      mcpExamples: [
        ['Tìm risk', 'Tôi đổi tên OrderService.createOrder. Có gì bị ảnh hưởng?', 'get_impact_analysis', 'Agent sẽ báo caller, route/test liên quan và bước verify nên chạy trước khi sửa.'], ['Trace API', 'POST /api/orders đi tới database qua đâu?', 'trace_endpoint', 'Agent sẽ trả controller, service call, repository boundary và cảnh báo mapping mơ hồ.'], ['Giải thích build lỗi', 'Giải thích lỗi Maven này và chỉ code bị ảnh hưởng.', 'explain_compile_error', 'Agent sẽ map dòng compiler tới symbol, caller và lệnh verify nhỏ nhất.'],
      ],
      manualTitle: '2C. Streamable HTTP thủ công', manualBody: 'PROJECT_API_KEY phải là key active của đúng project cần dùng. Lưu key trong secret/environment store của IDE, không commit vào workspace.',
      keysTitle: 'Đổi key và xử lý lỗi', keysBody: 'Sau key change, restart hoặc reload kết nối MCP của IDE. Key đã xóa, rotate, disable hoặc hết hạn sẽ bị từ chối. Browser selector chỉ trả về key thuộc tài khoản đang đăng nhập; MCP cũng từ chối request trỏ tới project khác với project được bind vào key.',
      keyMeaning: 'Ở chế độ HTTP thủ công, thay giá trị X-API-Key rồi reload MCP. Key xác định project; nó không phải OAuth secret, JWT secret hay credential dùng chung toàn tài khoản.',
      creditTitle: 'Cơ chế trừ credit', creditBody: 'MCP call có tính phí sẽ tính giá MCP_TOOL_CALL và reserve phần credit trước khi chạy tool. Ledger ghi channel MCP và project đã bind. Nếu debit thất bại thì tool không chạy; nếu tool lỗi sau khi đã reserve debit thì credit vẫn bị trừ.',
      troubleshootingTitle: 'Các lỗi thường gặp', troubleshootingBody: 'Chạy lệnh chẩn đoán nhỏ nhất trước. Các lệnh và thông báo dưới đây khớp với behavior hiện tại của CLI.',
      troubleshooting: [
        ['npm báo EEXIST: file already exists', 'Một command shim global cũ đang chặn cập nhật. Gỡ package, nếu shim VibeGraph còn thì chỉ xóa các shim VibeGraph, rồi cài lại.', 'npm uninstall -g vibegraph-cli\nRemove-Item "$env:APPDATA\\npm\\vibegraph.cmd","$env:APPDATA\\npm\\vibegraph.ps1","$env:APPDATA\\npm\\vibegraph-cli.cmd","$env:APPDATA\\npm\\vibegraph-cli.ps1" -Force -ErrorAction SilentlyContinue\nnpm install -g vibegraph-cli@latest'],
        ['Interactive shell báo Unknown command: vibegraph', 'Trong prompt interactive, chỉ nhập lệnh, không thêm tên executable. Prefix chỉ dùng ở terminal bình thường.', 'vibegraph> push\nvibegraph> key status\nvibegraph> doctor'],
        ['Đã add MCP nhưng không thấy tool', 'Chạy probe CLI rồi reload MCP server trong IDE. Nếu probe ready mà IDE vẫn trống, IDE đang đọc file config khác hoặc chưa restart. Khi tool đã hiện, gọi list_projects một lần từ IDE.', 'vibegraph mcp doctor\nvibegraph mcp install cursor\n# Restart hoặc reload MCP server trong IDE\n# Sau đó gọi list_projects'],
        ['MCP doctor báo key không hợp lệ', 'Key đã bị xóa, rotate, disable, hết hạn hoặc không thuộc tài khoản đang đăng nhập. Chọn lại key active thuộc tài khoản.', 'vibegraph key change\nvibegraph mcp doctor'],
        ['projects list trả HTTP 401', 'Quản lý project dùng account JWT; project API key bị giới hạn theo project và không phải session dùng chung tài khoản.', 'vibegraph login --email <email> --password <password>\nvibegraph projects list'],
      ],
      videosTitle: 'Video hướng dẫn — sẽ quay sau', videosBody: 'Mỗi card là một phiên quay riêng. Chỉ khi bạn nhắn số tương ứng mình mới thao tác trên Chrome và dừng ở điểm bạn có thể lưu video.',
      videoFooter: 'Điều kiện, kết quả mong đợi và điểm dừng OBS sẽ được chuẩn bị trước khi quay.',
      videos: [
        ['1', 'Cài CLI và đăng nhập trình duyệt', 'npm install -g vibegraph-cli → vibegraph login'], ['2', 'Chọn hoặc đổi project key', 'vibegraph key list → vibegraph key change'], ['3', 'Push một project thật', 'vibegraph push'], ['4', 'Cài MCP cho Cursor', 'vibegraph mcp install cursor'], ['5', 'Cài MCP cho VS Code hoặc IDE generic', 'vibegraph mcp install vscode|generic'], ['6', 'Cấu hình MCP HTTP thủ công', 'Dán JSON và thay <PROJECT_API_KEY>'], ['7', 'Gọi tool và kiểm tra credit', 'Chỉ quay với tài khoản/project test an toàn'],
      ],
    },
  },
} as const
