export const publicSiteCopy = {
  'en-US': {
    nav: { workflow: 'Workflow', proof: 'What is verified', docs: 'Docs' },
    actions: { login: 'Log in', dashboard: 'Open dashboard', readDocs: 'Read the production setup' },
    landing: {
      skip: 'Skip to content',
      heroEyebrow: 'SOURCE-CODE INTELLIGENCE / VIBEGRAPH.TECH',
      heroTitle: 'See your code as a graph.',
      heroBody: 'VibeGraph maps Java projects into searchable classes, methods, and relationships, then exposes impact and context through the dashboard and MCP.',
      heroNote: 'Project API keys stay scoped to one project. The CLI proxy keeps the raw key out of generated IDE JSON.',
      graphTitle: 'Interactive architecture graph',
      graphSubtitle: 'Select a node to inspect its connected surface.',
      graphSelected: 'Selected symbol',
      graphHint: 'Click a node · press Enter to focus',
      verifiedWorkflow: 'Documented VibeGraph workflow',
      verifiedLabel: 'documented workflow',
      loginSuccess: 'Authenticated in browser',
      selectedKey: 'Selected: <owned project key>',
      proxySuccess: 'MCP proxy written without raw key',
      consoleFooter: 'CLI → project key → MCP proxy → analyzed project',
      workflowEyebrow: 'THE WORKFLOW',
      workflowTitle: 'From a repository to a dependable context surface.',
      workflowBody: 'Each step maps to a real product surface already present in the repository and documented CLI.',
      flows: [
        ['01', 'Import a Java project', 'Use the web app, CLI Push, an archive, or a public GitHub URL to create the project graph.'],
        ['02', 'Read the graph', 'Explore classes, methods, relationships, source snippets, and execution-flow context in the dashboard.'],
        ['03', 'Connect an agent', 'Authenticate with a project-bound key, then let an MCP client query the same analyzed project.'],
      ],
      proofEyebrow: 'NO MARKETING NUMBERS',
      proofTitle: 'What this page can prove today.',
      proofBody: 'We removed simulated counters and demo output from the public promise. These are the implementation facts we can point to.',
      proofPoints: [
        'Spring Boot backend with a Neo4j graph store',
        'Vue 3 dashboard with Sigma.js graph rendering',
        'MCP server at /mcp with project ownership checks',
        'CLI commands for login, key selection, push, watch, and MCP install',
      ],
      ctaEyebrow: 'NEXT STEP',
      ctaTitle: 'Ready to work from the same graph?',
      ctaBody: 'Open the dashboard if you already have an account, or start with the documented browser login and project-key flow.',
      footer: 'Source-code intelligence for the vibe-coding era.',
      documentation: 'Documentation',
    },
    docs: {
      navLabel: 'Documentation navigation', back: 'Back to VibeGraph', onPage: 'On this page', titleLabel: 'Production docs',
      sideLinks: ['Release status', 'Install and login', 'CLI Push / Watch', 'MCP setup', 'Key changes and errors', 'Video plan'],
      eyebrow: 'VIBEGRAPH.TECH / DOCUMENTATION', title: 'Install the CLI. Point your IDE at the right project.',
      intro: 'This guide only documents flows present in the VibeGraph CLI, backend tests, or repository docs. It does not promise a feature that has not been verified.',
      releaseTitle: 'Release status checked locally',
      releaseBody: 'The repository package is named vibegraph-cli. At this build check, npm view vibegraph-cli version returned HTTP 404 from the npm registry. Until the package is published, install from the repository with npm install -g ./vibegraph-cli.',
      installTitle: 'Install and login', installLead: 'Production browser login proves the signed-in user owns the project key before the CLI stores it.',
      installBody: 'vibegraph login opens the browser authorization flow. After sign-in, choose an active project key owned by your account. Raw-key shortcuts are rejected because a key alone cannot prove account ownership.',
      pushTitle: 'CLI Push and Watch', pushLead: 'The selected project-bound key is used for root-only push and watch commands.',
      pushBody: 'The CLI safety rules skip secrets, archives, binary files, symlinks, build folders, and files over the configured limit. Press Ctrl+C to stop watch mode.',
      mcpTitle: 'MCP setup', mcpLead: 'Recommended: use the local stdio proxy. It reuses the selected CLI key and generated JSON does not contain the raw key.',
      mcpBody: "For an IDE not listed, run vibegraph mcp config and paste the generated stdio JSON into that IDE's MCP settings.",
      manualTitle: 'Manual Streamable HTTP', manualBody: 'PROJECT_API_KEY must be an active key created for the exact project. Store it in the IDE secret/environment store, not in a committed workspace file.',
      keysTitle: 'Change keys and recover from errors',
      keysBody: "After key change, restart or reload the IDE MCP connection. Deleted, rotated, disabled, or expired keys are rejected. The browser selector only returns keys owned by the signed-in account, and MCP rejects a tool request that targets a project different from the key's bound project.",
      keyMeaning: 'In manual HTTP mode, replace the X-API-Key value and reload MCP. The key identifies the project; it is not an OAuth secret, JWT secret, or account-wide credential.',
      creditTitle: 'Credit metering', creditBody: 'Metered MCP calls calculate the MCP_TOOL_CALL price and reserve the credit debit before running the delegated tool. The ledger records the MCP channel and bound project. If the debit fails, the tool does not run; a tool failure after the reserved debit remains charged.',
      videosTitle: 'Tutorial videos — will be recorded later', videosBody: 'Each card is a separate recording session. I will only operate Chrome after you send its number, then stop where you can save the video.',
      videoFooter: 'Prerequisites, expected result, and the OBS stop point will be prepared before recording.',
      videos: [
        ['1', 'Install the CLI and complete browser login', 'npm install -g vibegraph-cli → vibegraph login'],
        ['2', 'Select or change the project key', 'vibegraph key list → vibegraph key change'],
        ['3', 'Push a real project', 'vibegraph push --root ./your-project'],
        ['4', 'Install MCP for Cursor', 'vibegraph mcp install cursor'],
        ['5', 'Install MCP for VS Code or a generic IDE', 'vibegraph mcp install vscode|generic'],
        ['6', 'Configure MCP HTTP manually', 'Paste JSON and replace <PROJECT_API_KEY>'],
        ['7', 'Call a tool and inspect credits', 'Only with a safe test account/project'],
      ],
    },
  },
  'vi-VN': {
    nav: { workflow: 'Quy trình', proof: 'Bằng chứng', docs: 'Tài liệu' },
    actions: { login: 'Đăng nhập', dashboard: 'Mở dashboard', readDocs: 'Xem hướng dẫn production' },
    landing: {
      skip: 'Bỏ qua điều hướng', heroEyebrow: 'TRÍ TUỆ MÃ NGUỒN / VIBEGRAPH.TECH',
      heroTitle: 'Hiểu code qua graph.',
      heroBody: 'VibeGraph ánh xạ project Java thành class, method và relationship có thể tìm kiếm, sau đó cung cấp impact và context qua dashboard và MCP.',
      heroNote: 'API key được giới hạn theo từng project. CLI proxy không ghi raw key vào JSON IDE được tạo.',
      graphTitle: 'Graph kiến trúc tương tác',
      graphSubtitle: 'Chọn một node để xem vùng liên kết của nó.',
      graphSelected: 'Symbol đang chọn',
      graphHint: 'Bấm node · nhấn Enter để focus',
      verifiedWorkflow: 'Quy trình CLI/MCP được tài liệu hóa', verifiedLabel: 'quy trình được tài liệu hóa',
      loginSuccess: 'Xác thực thành công trên trình duyệt', selectedKey: 'Đã chọn: <project key thuộc tài khoản>',
      proxySuccess: 'Đã ghi MCP proxy, không chứa raw key', consoleFooter: 'CLI → project key → MCP proxy → project đã phân tích',
      workflowEyebrow: 'QUY TRÌNH', workflowTitle: 'Từ repository đến một nguồn context đáng tin cậy.',
      workflowBody: 'Mỗi bước đều tương ứng với một bề mặt sản phẩm có thật trong repository và CLI hiện tại.',
      flows: [
        ['01', 'Import project Java', 'Dùng web app, CLI Push, archive hoặc URL GitHub public để tạo project graph.'],
        ['02', 'Đọc graph', 'Khám phá class, method, relationship, source snippet và execution-flow context trên dashboard.'],
        ['03', 'Kết nối agent', 'Xác thực bằng project key, sau đó cho MCP client truy vấn đúng project đã phân tích.'],
      ],
      proofEyebrow: 'KHÔNG DÙNG SỐ LIỆU MARKETING', proofTitle: 'Những gì trang này chứng minh được hôm nay.',
      proofBody: 'Các counter và output demo mô phỏng đã bị loại khỏi lời hứa công khai. Đây là các dữ kiện có thể đối chiếu trong implementation.',
      proofPoints: ['Backend Spring Boot với graph store Neo4j', 'Dashboard Vue 3 render graph bằng Sigma.js', 'MCP server tại /mcp có kiểm tra quyền sở hữu project', 'CLI có lệnh login, chọn key, push, watch và cài MCP'],
      ctaEyebrow: 'BƯỚC TIẾP THEO', ctaTitle: 'Sẵn sàng làm việc trên cùng một graph?',
      ctaBody: 'Mở dashboard nếu bạn đã có tài khoản, hoặc bắt đầu bằng quy trình browser login và project key trong tài liệu.',
      footer: 'Trí tuệ mã nguồn cho thời đại vibe coding.', documentation: 'Tài liệu',
    },
    docs: {
      navLabel: 'Điều hướng tài liệu', back: 'Về trang chủ', onPage: 'Trong trang này', titleLabel: 'Tài liệu production',
      sideLinks: ['Trạng thái phát hành', 'Cài đặt và đăng nhập', 'CLI Push / Watch', 'Cài MCP', 'Đổi key và xử lý lỗi', 'Kế hoạch video'],
      eyebrow: 'VIBEGRAPH.TECH / TÀI LIỆU', title: 'Cài CLI. Trỏ IDE vào đúng project.',
      intro: 'Hướng dẫn này chỉ ghi các flow có trong VibeGraph CLI, backend test hoặc tài liệu repository. Không hứa một chức năng chưa được kiểm chứng.',
      releaseTitle: 'Trạng thái phát hành đã kiểm tra', releaseBody: 'Package trong repository có tên vibegraph-cli. Tại lần kiểm tra build này, npm view vibegraph-cli version trả HTTP 404 từ npm registry. Trước khi package được publish, hãy cài từ repository bằng npm install -g ./vibegraph-cli.',
      installTitle: 'Cài đặt và đăng nhập', installLead: 'Browser login production chứng minh người đang đăng nhập sở hữu project key trước khi CLI lưu key.',
      installBody: 'vibegraph login mở luồng xác nhận trên trình duyệt. Sau khi đăng nhập, chọn một project key active thuộc tài khoản của bạn. Các cách nhập raw key bị từ chối vì bản thân key không chứng minh được quyền sở hữu tài khoản.',
      pushTitle: 'CLI Push và Watch', pushLead: 'Project key đã chọn được dùng cho các lệnh push và watch chỉ cần root path.',
      pushBody: 'CLI tự bỏ qua secret, archive, binary, symlink, thư mục build và file vượt giới hạn cấu hình. Nhấn Ctrl+C để dừng watch mode.',
      mcpTitle: 'Cài MCP', mcpLead: 'Khuyến nghị dùng local stdio proxy. Nó dùng lại key đã chọn trong CLI và JSON được tạo không chứa raw key.',
      mcpBody: 'Với IDE chưa có preset, chạy vibegraph mcp config rồi dán JSON stdio được tạo vào phần MCP settings của IDE.',
      manualTitle: 'Streamable HTTP thủ công', manualBody: 'PROJECT_API_KEY phải là key active của đúng project cần dùng. Lưu key trong secret/environment store của IDE, không commit vào workspace.',
      keysTitle: 'Đổi key và xử lý lỗi', keysBody: 'Sau key change, restart hoặc reload kết nối MCP của IDE. Key đã xóa, rotate, disable hoặc hết hạn sẽ bị từ chối. Browser selector chỉ trả về key thuộc tài khoản đang đăng nhập; MCP cũng từ chối request trỏ tới project khác với project được bind vào key.',
      keyMeaning: 'Ở chế độ HTTP thủ công, thay giá trị X-API-Key rồi reload MCP. Key xác định project; nó không phải OAuth secret, JWT secret hay credential dùng chung toàn tài khoản.',
      creditTitle: 'Cơ chế trừ credit', creditBody: 'MCP call có tính phí sẽ tính giá MCP_TOOL_CALL và reserve phần credit trước khi chạy tool. Ledger ghi channel MCP và project đã bind. Nếu debit thất bại thì tool không chạy; nếu tool lỗi sau khi đã reserve debit thì credit vẫn bị trừ.',
      videosTitle: 'Video hướng dẫn — sẽ quay sau', videosBody: 'Mỗi card là một phiên quay riêng. Chỉ khi bạn nhắn số tương ứng mình mới thao tác trên Chrome và dừng ở điểm bạn có thể lưu video.',
      videoFooter: 'Điều kiện, kết quả mong đợi và điểm dừng OBS sẽ được chuẩn bị trước khi quay.',
      videos: [
        ['1', 'Cài CLI và đăng nhập trình duyệt', 'npm install -g vibegraph-cli → vibegraph login'], ['2', 'Chọn hoặc đổi project key', 'vibegraph key list → vibegraph key change'], ['3', 'Push một project thật', 'vibegraph push --root ./your-project'], ['4', 'Cài MCP cho Cursor', 'vibegraph mcp install cursor'], ['5', 'Cài MCP cho VS Code hoặc IDE generic', 'vibegraph mcp install vscode|generic'], ['6', 'Cấu hình MCP HTTP thủ công', 'Dán JSON và thay <PROJECT_API_KEY>'], ['7', 'Gọi tool và kiểm tra credit', 'Chỉ quay với tài khoản/project test an toàn'],
      ],
    },
  },
} as const
