export const publicSiteCopy = {
  'en-US': {
    nav: { workflow: 'Workflow', proof: 'What is verified', docs: 'Docs' },
    actions: { login: 'Log in', dashboard: 'Open dashboard', readDocs: 'Read the production setup' },
    landing: {
      skip: 'Skip to content',
      heroEyebrow: 'SOURCE-CODE INTELLIGENCE / VIBEGRAPH.TECH',
      heroTitle: 'See your code as a graph.',
      heroBody: 'VibeGraph maps Java projects into searchable classes, methods, and relationships, then exposes impact and context through the dashboard and MCP.',
      heroNote: 'Project API keys stay scoped to one project. The CLI proxy keeps the raw key out of generated IDE JSON.',
      graphTitle: 'Interactive architecture graph',
      graphSubtitle: 'Select a node to inspect its connected surface.',
      graphSelected: 'Selected symbol',
      graphHint: 'Click a node · press Enter to focus',
      verifiedWorkflow: 'Documented VibeGraph workflow',
      verifiedLabel: 'documented workflow',
      loginSuccess: 'Authenticated in browser',
      selectedKey: 'Selected: <owned project key>',
      proxySuccess: 'MCP proxy written without raw key',
      consoleFooter: 'CLI → project key → MCP proxy → analyzed project',
      workflowEyebrow: 'THE WORKFLOW',
      workflowTitle: 'From a repository to a dependable context surface.',
      workflowBody: 'Each step maps to a real product surface already present in the repository and documented CLI.',
      flows: [
        ['01', 'Import a Java project', 'Use the web app, CLI Push, an archive, or a public GitHub URL to create the project graph.'],
        ['02', 'Read the graph', 'Explore classes, methods, relationships, source snippets, and execution-flow context in the dashboard.'],
        ['03', 'Connect an agent', 'Authenticate with a project-bound key, then let an MCP client query the same analyzed project.'],
      ],
      proofEyebrow: 'NO MARKETING NUMBERS',
      proofTitle: 'What this page can prove today.',
      proofBody: 'We removed simulated counters and demo output from the public promise. These are the implementation facts we can point to.',
      proofPoints: [
        'Spring Boot backend with a Neo4j graph store',
        'Vue 3 dashboard with Sigma.js graph rendering',
        'MCP server at /mcp with project ownership checks',
        'CLI commands for login, key selection, push, watch, and MCP install',
      ],
      ctaEyebrow: 'NEXT STEP',
      ctaTitle: 'Ready to work from the same graph?',
      ctaBody: 'Open the dashboard if you already have an account, or start with the documented browser login and project-key flow.',
      footer: 'Source-code intelligence for the vibe-coding era.',
      documentation: 'Documentation',
    },
    docs: {
      navLabel: 'Documentation navigation', back: 'Back to VibeGraph', onPage: 'On this page', titleLabel: 'Production docs',
      sideLinks: ['Release status', 'Install and login', 'CLI Push / Watch', 'CLI commands', 'MCP setup', 'Key changes and errors', 'Troubleshooting', 'Video plan'],
      eyebrow: 'VIBEGRAPH.TECH / DOCUMENTATION', title: 'Install the CLI. Point your IDE at the right project.',
      intro: 'This guide only documents flows present in the VibeGraph CLI, backend tests, or repository docs. It does not promise a feature that has not been verified.',
      releaseTitle: 'Release status checked locally',
      releaseBody: 'The npm registry currently serves vibegraph-cli@0.1.0. Install it globally with npm install -g vibegraph-cli, then run vibegraph login to choose a project key in the browser. The improved mcp doctor probe and stale-config repair are in CLI 0.1.1 and require that version to be published before end users can use them.',
      installTitle: 'Install and login', installLead: 'Production browser login proves the signed-in user owns the project key before the CLI stores it.',
      installBody: 'vibegraph login opens the browser authorization flow. After sign-in, choose an active project key owned by your account. Raw-key shortcuts are rejected because a key alone cannot prove account ownership.',
      updateTitle: 'Update an existing CLI', updateBody: 'For a clean update, remove the old global package before installing the latest published version. This avoids stale Windows command shims. Never paste a project API key into npm.',
      pushTitle: 'CLI Push and Watch', pushLead: 'Run push or watch inside the project folder. The selected project key decides which VibeGraph project receives the changes.',
      firstPushTitle: 'First push', firstPushBody: 'Before the first push, create the destination project and an active project API key in the web dashboard. Browser login selects that owned key. Dry-run scans the folder without sending a patch; push sends the changed files to the key-bound project.',
      updatePushTitle: 'Update the analyzed project', updatePushBody: 'After editing source files, run push again from the same folder. The CLI compares its local snapshot and sends only changed/deleted files. Use watch when you want continuous updates.',
      pushMcpTitle: 'How Push and MCP work together', pushMcpBody: 'Push updates the project graph. MCP reads that same analyzed project through the selected key. Push is not an MCP install step: configure MCP once, then push whenever the code changes.',
      pushBody: 'The CLI safety rules skip secrets, archives, binary files, symlinks, build folders, and files over the configured limit. Press Ctrl+C to stop watch mode.',
      commandsTitle: 'VibeGraph CLI command reference', commandsBody: 'Run these commands in a normal terminal. The CLI uses the current folder by default, so the common workflow stays short. Inside the interactive vibegraph> shell, omit the executable prefix and enter only the command text.',
      commands: [
        ['vibegraph --version', 'Show the installed CLI version.'], ['vibegraph help', 'Show the complete command reference.'], ['vibegraph config show', 'Show the API URL, config path, account state, and masked key state.'], ['vibegraph config set-url <url>', 'Set the backend URL; production uses https://api.vibegraph.tech.'], ['vibegraph config reset', 'Remove the local CLI config file.'], ['vibegraph register --email <email> --password <password> --name <name>', 'Create an account and save its account session.'], ['vibegraph login', 'Open browser login and select an owned project API key.'], ['vibegraph login --email <email> --password <password>', 'Sign in directly with account credentials for account-level project management.'], ['vibegraph logout', 'Clear the saved account session, project key, project selection, and cached key metadata.'], ['vibegraph me', 'Show the account attached to a valid JWT session.'], ['vibegraph doctor', 'Check backend health, JWT session validity, and selected API key status.'], ['vibegraph key list', 'Show cached masked key/project metadata.'], ['vibegraph key change', 'Refresh owned keys and select another project key.'], ['vibegraph key status', 'Show masked selected-key state.'], ['vibegraph key clear', 'Clear the selected project key; this is the same operation as auth clear.'], ['vibegraph auth status', 'Show selected API key status and whether a legacy account token is stored.'], ['vibegraph auth clear', 'Clear the selected project key without deleting the account.'], ['vibegraph push', 'Scan the current folder and send a patch to the selected project key.'], ['vibegraph push --dry-run', 'Preview changed, deleted, and skipped files without sending a patch.'], ['vibegraph watch', 'Watch the current folder and push changes continuously.'], ['vibegraph ignore init', 'Create a .vibegraphignore file for project-specific scan exclusions.'], ['vibegraph projects list', 'List projects through the account session, not the project API key.'], ['vibegraph projects create --path <backendPath>', 'Register a path visible to the backend host; this is not a local-folder upload.'], ['vibegraph projects import-local --path <backendPath>', 'Import a backend/container-visible path.'], ['vibegraph projects analyze <projectId>', 'Trigger analysis for a project through the account session.'], ['vibegraph projects status <projectId>', 'Show project status and available graph counts.'], ['vibegraph projects delete <projectId>', 'Delete a project through the account session.'], ['vibegraph mcp install <cursor|vscode|generic>', 'Write/update an IDE MCP config and verify the handshake.'], ['vibegraph mcp config <cursor|vscode|generic>', 'Print JSON for manual copy/paste; it does not edit IDE files.'], ['vibegraph mcp doctor', 'Verify MCP initialize/tools/list and report the available tool count.'], ['vibegraph mcp-proxy --stdio', 'Internal stdio bridge used by IDE MCP clients; do not type it inside the interactive shell.'],
      ],
      mcpTitle: 'MCP setup', mcpLead: 'There are two ways to add VibeGraph MCP. Automatic install edits the IDE config for you. Manual setup means either generating stdio JSON or pasting the remote HTTP JSON. Choose one method per VibeGraph server entry, then restart or reload the IDE MCP connection.',
      autoMcpTitle: '1. Automatic install', autoMcpBody: 'After vibegraph login, the CLI writes or updates the correct config file and runs an initialize/tools-list check. Cursor uses mcpServers in ~/.cursor/mcp.json; VS Code uses servers in .vscode/mcp.json; generic writes mcp.json unless --path is supplied.',
      generatedMcpTitle: '2A. Manual stdio config — generate JSON', generatedMcpBody: 'mcp config only prints configuration; it does not edit any IDE file. generic and cursor output the standard mcpServers shape. vscode outputs VS Code\'s servers shape. Paste the complete object into the IDE MCP settings. This is the manual version of the same local CLI proxy used by automatic install.',
      mcpBody: 'If tools do not appear after installation, run vibegraph mcp doctor, then restart or reload the IDE MCP server. Do not paste the vibegraph> prompt and do not nest a second mcpServers object.',
      manualTitle: '2B. Manual Streamable HTTP', manualBody: 'PROJECT_API_KEY must be an active key created for the exact project. Store it in the IDE secret/environment store, not in a committed workspace file.',
      keysTitle: 'Change keys and recover from errors',
      keysBody: "After key change, restart or reload the IDE MCP connection. Deleted, rotated, disabled, or expired keys are rejected. The browser selector only returns keys owned by the signed-in account, and MCP rejects a tool request that targets a project different from the key's bound project.",
      keyMeaning: 'In manual HTTP mode, replace the X-API-Key value and reload MCP. The key identifies the project; it is not an OAuth secret, JWT secret, or account-wide credential.',
      creditTitle: 'Credit metering', creditBody: 'Metered MCP calls calculate the MCP_TOOL_CALL price and reserve the credit debit before running the delegated tool. The ledger records the MCP channel and bound project. If the debit fails, the tool does not run; a tool failure after the reserved debit remains charged.',
      troubleshootingTitle: 'Common fixes', troubleshootingBody: 'Use the smallest diagnostic command first. These commands and messages match the current CLI behavior.',
      troubleshooting: [
        ['npm says EEXIST: file already exists', 'A stale global command shim is blocking the update. Uninstall the package, remove only the VibeGraph shims if they remain, then install again.', 'npm uninstall -g vibegraph-cli\nRemove-Item "$env:APPDATA\\npm\\vibegraph.cmd","$env:APPDATA\\npm\\vibegraph.ps1","$env:APPDATA\\npm\\vibegraph-cli.cmd","$env:APPDATA\\npm\\vibegraph-cli.ps1" -Force -ErrorAction SilentlyContinue\nnpm install -g vibegraph-cli@latest'],
        ['The terminal says Unknown command: vibegraph', 'Inside the interactive prompt, type the command without the executable prefix. The prefix is only for a normal terminal command.', 'vibegraph> push\nvibegraph> key status\nvibegraph> doctor'],
        ['MCP was added but no tools appear', 'Run the CLI probe, then reload the IDE MCP server. If the probe is ready but the IDE is empty, the IDE is reading another config file or has not restarted.', 'vibegraph mcp doctor\nvibegraph mcp install cursor\n# Restart or reload the IDE MCP server'],
        ['MCP doctor says the key is invalid', 'The selected project key was deleted, rotated, disabled, expired, or is not owned by the signed-in account. Select a fresh owned key.', 'vibegraph key change\nvibegraph mcp doctor'],
        ['projects list returns HTTP 401', 'Project management uses an account JWT; a project API key is intentionally project-bound and is not an account-wide session.', 'vibegraph login --email <email> --password <password>\nvibegraph projects list'],
      ],
      videosTitle: 'Tutorial videos — will be recorded later', videosBody: 'Each card is a separate recording session. I will only operate Chrome after you send its number, then stop where you can save the video.',
      videoFooter: 'Prerequisites, expected result, and the OBS stop point will be prepared before recording.',
      videos: [
        ['1', 'Install the CLI and complete browser login', 'npm install -g vibegraph-cli → vibegraph login'],
        ['2', 'Select or change the project key', 'vibegraph key list → vibegraph key change'],
        ['3', 'Push a real project', 'vibegraph push'],
        ['4', 'Install MCP for Cursor', 'vibegraph mcp install cursor'],
        ['5', 'Install MCP for VS Code or a generic IDE', 'vibegraph mcp install vscode|generic'],
        ['6', 'Configure MCP HTTP manually', 'Paste JSON and replace <PROJECT_API_KEY>'],
        ['7', 'Call a tool and inspect credits', 'Only with a safe test account/project'],
      ],
    },
  },
  'vi-VN': {
    nav: { workflow: 'Quy trình', proof: 'Bằng chứng', docs: 'Tài liệu' },
    actions: { login: 'Đăng nhập', dashboard: 'Mở dashboard', readDocs: 'Xem hướng dẫn production' },
    landing: {
      skip: 'Bỏ qua điều hướng', heroEyebrow: 'TRÍ TUỆ MÃ NGUỒN / VIBEGRAPH.TECH',
      heroTitle: 'Hiểu code qua graph.',
      heroBody: 'VibeGraph ánh xạ project Java thành class, method và relationship có thể tìm kiếm, sau đó cung cấp impact và context qua dashboard và MCP.',
      heroNote: 'API key được giới hạn theo từng project. CLI proxy không ghi raw key vào JSON IDE được tạo.',
      graphTitle: 'Graph kiến trúc tương tác',
      graphSubtitle: 'Chọn một node để xem vùng liên kết của nó.',
      graphSelected: 'Symbol đang chọn',
      graphHint: 'Bấm node · nhấn Enter để focus',
      verifiedWorkflow: 'Quy trình CLI/MCP được tài liệu hóa', verifiedLabel: 'quy trình được tài liệu hóa',
      loginSuccess: 'Xác thực thành công trên trình duyệt', selectedKey: 'Đã chọn: <project key thuộc tài khoản>',
      proxySuccess: 'Đã ghi MCP proxy, không chứa raw key', consoleFooter: 'CLI → project key → MCP proxy → project đã phân tích',
      workflowEyebrow: 'QUY TRÌNH', workflowTitle: 'Từ repository đến một nguồn context đáng tin cậy.',
      workflowBody: 'Mỗi bước đều tương ứng với một bề mặt sản phẩm có thật trong repository và CLI hiện tại.',
      flows: [
        ['01', 'Import project Java', 'Dùng web app, CLI Push, archive hoặc URL GitHub public để tạo project graph.'],
        ['02', 'Đọc graph', 'Khám phá class, method, relationship, source snippet và execution-flow context trên dashboard.'],
        ['03', 'Kết nối agent', 'Xác thực bằng project key, sau đó cho MCP client truy vấn đúng project đã phân tích.'],
      ],
      proofEyebrow: 'KHÔNG DÙNG SỐ LIỆU MARKETING', proofTitle: 'Những gì trang này chứng minh được hôm nay.',
      proofBody: 'Các counter và output demo mô phỏng đã bị loại khỏi lời hứa công khai. Đây là các dữ kiện có thể đối chiếu trong implementation.',
      proofPoints: ['Backend Spring Boot với graph store Neo4j', 'Dashboard Vue 3 render graph bằng Sigma.js', 'MCP server tại /mcp có kiểm tra quyền sở hữu project', 'CLI có lệnh login, chọn key, push, watch và cài MCP'],
      ctaEyebrow: 'BƯỚC TIẾP THEO', ctaTitle: 'Sẵn sàng làm việc trên cùng một graph?',
      ctaBody: 'Mở dashboard nếu bạn đã có tài khoản, hoặc bắt đầu bằng quy trình browser login và project key trong tài liệu.',
      footer: 'Trí tuệ mã nguồn cho thời đại vibe coding.', documentation: 'Tài liệu',
    },
    docs: {
      navLabel: 'Điều hướng tài liệu', back: 'Về trang chủ', onPage: 'Trong trang này', titleLabel: 'Tài liệu production',
      sideLinks: ['Trạng thái phát hành', 'Cài đặt và đăng nhập', 'CLI Push / Watch', 'Danh sách lệnh CLI', 'Cài MCP', 'Đổi key và xử lý lỗi', 'Xử lý lỗi thường gặp', 'Kế hoạch video'],
      eyebrow: 'VIBEGRAPH.TECH / TÀI LIỆU', title: 'Cài CLI. Trỏ IDE vào đúng project.',
      intro: 'Hướng dẫn này chỉ ghi các flow có trong VibeGraph CLI, backend test hoặc tài liệu repository. Không hứa một chức năng chưa được kiểm chứng.',
      releaseTitle: 'Trạng thái phát hành đã kiểm tra', releaseBody: 'npm registry hiện đang phục vụ vibegraph-cli@0.1.0. Cài global bằng npm install -g vibegraph-cli, sau đó chạy vibegraph login để chọn project key trên trình duyệt. Probe mcp doctor và cơ chế tự sửa config cũ nằm trong CLI 0.1.1, cần publish version đó trước khi người dùng cuối sử dụng.',
      installTitle: 'Cài đặt và đăng nhập', installLead: 'Browser login production chứng minh người đang đăng nhập sở hữu project key trước khi CLI lưu key.',
      installBody: 'vibegraph login mở luồng xác nhận trên trình duyệt. Sau khi đăng nhập, chọn một project key active thuộc tài khoản của bạn. Các cách nhập raw key bị từ chối vì bản thân key không chứng minh được quyền sở hữu tài khoản.',
      updateTitle: 'Cập nhật CLI đã cài', updateBody: 'Để cập nhật sạch, gỡ package global cũ trước khi cài bản published mới. Cách này tránh command shim Windows cũ. Không dán project API key vào npm.',
      pushTitle: 'CLI Push và Watch', pushLead: 'Chạy push hoặc watch ngay trong thư mục dự án. Project key đã chọn quyết định project VibeGraph nhận thay đổi.',
      firstPushTitle: 'Push lần đầu', firstPushBody: 'Trước lần push đầu, tạo project đích và một project API key active trên web dashboard. Browser login dùng để chọn key thuộc tài khoản đó. Dry-run quét thư mục nhưng không gửi patch; push gửi file thay đổi tới project được bind với key.',
      updatePushTitle: 'Cập nhật project đã phân tích', updatePushBody: 'Sau khi sửa source, chạy lại push trong cùng thư mục. CLI đối chiếu snapshot local và chỉ gửi file changed/deleted. Dùng watch nếu muốn cập nhật liên tục.',
      pushMcpTitle: 'Push kết hợp với MCP như thế nào', pushMcpBody: 'Push cập nhật graph của project. MCP đọc chính project đã phân tích đó bằng key đang chọn. Push không thay cho bước cài MCP: cài MCP một lần, sau đó push mỗi khi code thay đổi.',
      pushBody: 'CLI tự bỏ qua secret, archive, binary, symlink, thư mục build và file vượt giới hạn cấu hình. Nhấn Ctrl+C để dừng watch mode.',
      commandsTitle: 'Danh sách lệnh VibeGraph CLI', commandsBody: 'Chạy các lệnh này trong terminal bình thường. CLI tự dùng thư mục hiện tại nên workflow phổ biến không cần tham số đường dẫn. Trong interactive shell vibegraph>, bỏ phần tên executable và chỉ nhập nội dung lệnh.',
      commands: [
        ['vibegraph --version', 'Xem version CLI đang cài.'], ['vibegraph help', 'Xem toàn bộ danh sách lệnh.'], ['vibegraph config show', 'Xem API URL, config path, trạng thái account và key dạng masked.'], ['vibegraph config set-url <url>', 'Đặt URL backend; production dùng https://api.vibegraph.tech.'], ['vibegraph config reset', 'Xóa file config CLI trên máy.'], ['vibegraph register --email <email> --password <password> --name <name>', 'Tạo tài khoản và lưu account session.'], ['vibegraph login', 'Mở browser login và chọn project API key thuộc tài khoản.'], ['vibegraph login --email <email> --password <password>', 'Đăng nhập trực tiếp để dùng các lệnh quản lý project cấp tài khoản.'], ['vibegraph logout', 'Xóa account session, project key, project đang chọn và metadata key cache.'], ['vibegraph me', 'Xem tài khoản của JWT session còn hiệu lực.'], ['vibegraph doctor', 'Kiểm tra health backend, JWT session và trạng thái key đang chọn.'], ['vibegraph key list', 'Xem metadata key/project dạng masked đã cache.'], ['vibegraph key change', 'Refresh danh sách key thuộc tài khoản và chọn project khác.'], ['vibegraph key status', 'Xem trạng thái key đang chọn dạng masked.'], ['vibegraph key clear', 'Xóa project key đang chọn; cùng chức năng với auth clear.'], ['vibegraph auth status', 'Xem trạng thái project key và việc có lưu legacy account token hay không.'], ['vibegraph auth clear', 'Xóa project key đang chọn trên máy, không xóa tài khoản.'], ['vibegraph push', 'Quét thư mục hiện tại và gửi patch tới project của key đang chọn.'], ['vibegraph push --dry-run', 'Xem trước file changed, deleted và skipped mà không gửi patch.'], ['vibegraph watch', 'Theo dõi thư mục hiện tại và push thay đổi liên tục.'], ['vibegraph ignore init', 'Tạo .vibegraphignore để thêm quy tắc bỏ qua file riêng của project.'], ['vibegraph projects list', 'Liệt kê project bằng account session, không dùng project API key.'], ['vibegraph projects create --path <backendPath>', 'Đăng ký path mà backend host nhìn thấy; không phải upload thư mục local.'], ['vibegraph projects import-local --path <backendPath>', 'Import path mà backend/container nhìn thấy.'], ['vibegraph projects analyze <projectId>', 'Kích hoạt analyze project bằng account session.'], ['vibegraph projects status <projectId>', 'Xem trạng thái project và graph count hiện có.'], ['vibegraph projects delete <projectId>', 'Xóa project bằng account session.'], ['vibegraph mcp install <cursor|vscode|generic>', 'Ghi/cập nhật config MCP IDE và kiểm tra handshake.'], ['vibegraph mcp config <cursor|vscode|generic>', 'In JSON để copy/dán thủ công; không tự sửa file IDE.'], ['vibegraph mcp doctor', 'Kiểm tra MCP initialize/tools/list và báo số lượng tool.'], ['vibegraph mcp-proxy --stdio', 'Cầu nối stdio nội bộ cho IDE MCP; không nhập lệnh này trong interactive shell.'],
      ],
      mcpTitle: 'Cài MCP', mcpLead: 'Có hai cách thêm VibeGraph MCP. Cài tự động sẽ tự sửa file cấu hình IDE. Cài thủ công gồm gen JSON stdio hoặc dán JSON HTTP remote. Chọn một cách cho mỗi entry VibeGraph, sau đó restart hoặc reload kết nối MCP của IDE.',
      autoMcpTitle: '1. Cài tự động', autoMcpBody: 'Sau vibegraph login, CLI tự ghi hoặc cập nhật đúng file cấu hình rồi chạy kiểm tra initialize/tools-list. Cursor dùng mcpServers trong ~/.cursor/mcp.json; VS Code dùng servers trong .vscode/mcp.json; generic ghi mcp.json nếu không truyền --path.',
      generatedMcpTitle: '2A. Cấu hình stdio thủ công — gen JSON', generatedMcpBody: 'mcp config chỉ in cấu hình, không tự sửa file IDE. generic và cursor in dạng chuẩn mcpServers. vscode in dạng servers riêng của VS Code. Dán nguyên object được sinh ra vào MCP settings. Đây là cách thủ công của cùng local CLI proxy mà lệnh tự động sử dụng.',
      mcpBody: 'Nếu cài xong không thấy tool, chạy vibegraph mcp doctor rồi restart hoặc reload MCP server trong IDE. Không dán prompt vibegraph> và không lồng thêm một tầng mcpServers.',
      manualTitle: '2B. Streamable HTTP thủ công', manualBody: 'PROJECT_API_KEY phải là key active của đúng project cần dùng. Lưu key trong secret/environment store của IDE, không commit vào workspace.',
      keysTitle: 'Đổi key và xử lý lỗi', keysBody: 'Sau key change, restart hoặc reload kết nối MCP của IDE. Key đã xóa, rotate, disable hoặc hết hạn sẽ bị từ chối. Browser selector chỉ trả về key thuộc tài khoản đang đăng nhập; MCP cũng từ chối request trỏ tới project khác với project được bind vào key.',
      keyMeaning: 'Ở chế độ HTTP thủ công, thay giá trị X-API-Key rồi reload MCP. Key xác định project; nó không phải OAuth secret, JWT secret hay credential dùng chung toàn tài khoản.',
      creditTitle: 'Cơ chế trừ credit', creditBody: 'MCP call có tính phí sẽ tính giá MCP_TOOL_CALL và reserve phần credit trước khi chạy tool. Ledger ghi channel MCP và project đã bind. Nếu debit thất bại thì tool không chạy; nếu tool lỗi sau khi đã reserve debit thì credit vẫn bị trừ.',
      troubleshootingTitle: 'Các lỗi thường gặp', troubleshootingBody: 'Chạy lệnh chẩn đoán nhỏ nhất trước. Các lệnh và thông báo dưới đây khớp với behavior hiện tại của CLI.',
      troubleshooting: [
        ['npm báo EEXIST: file already exists', 'Một command shim global cũ đang chặn cập nhật. Gỡ package, nếu shim VibeGraph còn thì chỉ xóa các shim VibeGraph, rồi cài lại.', 'npm uninstall -g vibegraph-cli\nRemove-Item "$env:APPDATA\\npm\\vibegraph.cmd","$env:APPDATA\\npm\\vibegraph.ps1","$env:APPDATA\\npm\\vibegraph-cli.cmd","$env:APPDATA\\npm\\vibegraph-cli.ps1" -Force -ErrorAction SilentlyContinue\nnpm install -g vibegraph-cli@latest'],
        ['Interactive shell báo Unknown command: vibegraph', 'Trong prompt interactive, chỉ nhập lệnh, không thêm tên executable. Prefix chỉ dùng ở terminal bình thường.', 'vibegraph> push\nvibegraph> key status\nvibegraph> doctor'],
        ['Đã add MCP nhưng không thấy tool', 'Chạy probe CLI rồi reload MCP server trong IDE. Nếu probe ready mà IDE vẫn trống, IDE đang đọc file config khác hoặc chưa restart.', 'vibegraph mcp doctor\nvibegraph mcp install cursor\n# Restart hoặc reload MCP server trong IDE'],
        ['MCP doctor báo key không hợp lệ', 'Key đã bị xóa, rotate, disable, hết hạn hoặc không thuộc tài khoản đang đăng nhập. Chọn lại key active thuộc tài khoản.', 'vibegraph key change\nvibegraph mcp doctor'],
        ['projects list trả HTTP 401', 'Quản lý project dùng account JWT; project API key bị giới hạn theo project và không phải session dùng chung tài khoản.', 'vibegraph login --email <email> --password <password>\nvibegraph projects list'],
      ],
      videosTitle: 'Video hướng dẫn — sẽ quay sau', videosBody: 'Mỗi card là một phiên quay riêng. Chỉ khi bạn nhắn số tương ứng mình mới thao tác trên Chrome và dừng ở điểm bạn có thể lưu video.',
      videoFooter: 'Điều kiện, kết quả mong đợi và điểm dừng OBS sẽ được chuẩn bị trước khi quay.',
      videos: [
        ['1', 'Cài CLI và đăng nhập trình duyệt', 'npm install -g vibegraph-cli → vibegraph login'], ['2', 'Chọn hoặc đổi project key', 'vibegraph key list → vibegraph key change'], ['3', 'Push một project thật', 'vibegraph push'], ['4', 'Cài MCP cho Cursor', 'vibegraph mcp install cursor'], ['5', 'Cài MCP cho VS Code hoặc IDE generic', 'vibegraph mcp install vscode|generic'], ['6', 'Cấu hình MCP HTTP thủ công', 'Dán JSON và thay <PROJECT_API_KEY>'], ['7', 'Gọi tool và kiểm tra credit', 'Chỉ quay với tài khoản/project test an toàn'],
      ],
    },
  },
} as const
